steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', '${_DOCKERFILE}',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_LAYER}:${_TAG}',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_LAYER}:${_TAG}']

substitutions:
  _REGION: 'us-central1'
  _REPO: 'dataflow'
  _LAYER: 'bronze'
  _TAG: 'latest'
  _DOCKERFILE: 'Dockerfile.bronze'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_LAYER}:${_TAG}'
