# ci/cloudbuild.bronze.yaml

# Variáveis que serão substituídas na execução (ex: via Github Actions ou gcloud build)
# Defina estas variáveis no seu ambiente ou no acionador do Cloud Build.
# _PROJECT_ID: ID do seu projeto GCP.
# _GCS_TEMPLATE_BUCKET: Nome do seu bucket de templates (ex: bk-etl-hotelaria).
# _LOCATION: Região onde o Dataflow será executado (ex: us-central1).
# _TAG_NAME: Versão ou hash do commit (ex: latest ou $COMMIT_SHA).

steps:
# ----------------------------------------------------------------------
# PASSO 1: Configuração e Testes
# ----------------------------------------------------------------------
- id: 'Instalar Dependências e Rodar Testes'
  name: 'python' # Usamos uma imagem Python para instalar dependências e rodar testes
  entrypoint: bash
  args:
    - -c
    - |
      echo "Instalando dependências..."
      pip install -r src/bronze/requirements.txt
      pip install -e . # Instala o projeto localmente via setup.py
      
      echo "Rodando Testes da Camada Bronze..."
      # O pytest é comumente usado. Assumindo que você o incluiu no requirements.txt
      # Executa os testes unitários do Apache Beam
      python -m pytest tests/test_transforms_bronze.py
  dir: 'dataflow-pipelines' # Direciona o comando para a raiz do projeto

# ----------------------------------------------------------------------
# PASSO 2: Build da Imagem Docker
# ----------------------------------------------------------------------
- id: 'Buildar Imagem Docker'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_PROJECT_ID}/dataflow/bronze-hotelaria:$COMMIT_SHA'
    - '.' # O Dockerfile está em src/bronze/
  dir: 'dataflow-pipelines'

# ----------------------------------------------------------------------
# PASSO 3: Push da Imagem para o Google Container Registry (GCR)
# ----------------------------------------------------------------------
- id: 'Push da Imagem'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/${_PROJECT_ID}/dataflow/bronze-hotelaria:$COMMIT_SHA'
  dir: 'dataflow-pipelines'

# ----------------------------------------------------------------------
# PASSO 4: Criar o Flex Template no GCS
# ----------------------------------------------------------------------
- id: 'Criar Flex Template'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - -c
    - |
      gcloud dataflow flex-template build gs://${_GCS_TEMPLATE_BUCKET}/templates/bronze-hotelaria.json \
        --image 'gcr.io/${_PROJECT_ID}/dataflow/bronze-hotelaria:$COMMIT_SHA' \
        --sdk-language 'PYTHON' \
        --metadata-file 'src/bronze/metadata.json' \
        --region '${_LOCATION}'
  dir: 'dataflow-pipelines'

# ----------------------------------------------------------------------
# SAÍDA (Opcional)
# ----------------------------------------------------------------------
images:
  - 'gcr.io/${_PROJECT_ID}/dataflow/bronze-hotelaria:$COMMIT_SHA'

# ----------------------------------------------------------------------
# OPÇÕES DE BUILD: Define o logging para CLOUD_LOGGING_ONLY
# Resolve o erro 'build.service_account' ao usar SA personalizada.
# ----------------------------------------------------------------------
options:
  logging: CLOUD_LOGGING_ONLY